<Project>
    <!-- Each project deploys its own assemblies, runs regardless of which project triggered the build -->
    <Target Name="DeployAssembly" AfterTargets="Build">
        <ItemGroup>
            <AssemblyFiles Include="$(OutputPath)*.dll"/>
            <AssemblyFiles Include="$(OutputPath)*.so"/>
            <AssemblyFiles Include="$(OutputPath)*.dylib"/>
            <!--<PdbFiles Include="$(OutputPath)*.pdb"/>-->
        </ItemGroup>
        <MakeDir Directories="$(RimWorldModsPath)\PawnEditor\$(RimWorldVersion)\Assemblies"/>
        <Copy SourceFiles="@(AssemblyFiles)"
              DestinationFolder="$(RimWorldModsPath)\PawnEditor\$(RimWorldVersion)\Assemblies"
              SkipUnchangedFiles="true"/>
        <!--<Copy SourceFiles="@(PdbFiles)"
              DestinationFolder="$(RimWorldModsPath)\PawnEditor\$(RimWorldVersion)\Assemblies"
              SkipUnchangedFiles="true"/>-->
    </Target>
</Project>
