<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Void</RootNamespace>
        <AssemblyName>Void</AssemblyName>
        <ModName>Void</ModName>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>
    <PropertyGroup>
        <OutputPath>bin\</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Taffy\Taffy.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="EditCompileReload" Version="1.0.2"/>
        <PackageReference Include="EditCompileReload.CompilerPlugin" Version="1.0.2"/>
    </ItemGroup>
    <ItemGroup>
        <Publicize Include="Assembly-CSharp"/>
    </ItemGroup>
    <ItemGroup>
        <!-- Embed small icons used in the components directly into the dll. -->
        <EmbeddedResource Include="Textures\*.png"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4752-beta"/>
        <PackageReference Include="Lib.Harmony" Version="2.4.2"/>
    </ItemGroup>
</Project>
