name: Build mod

on:
  push:
    branches: ["feat/**"]
    paths:
      - "data/**"
      - "src/**"

jobs:
  build-mod:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore
        run: dotnet restore PawnEditor.sln

      - name: Build & Deploy
        env:
          RIMWORLD_MODS_PATH: ${{ github.workspace }}/artifact
        run: dotnet build PawnEditor.sln --configuration Release --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PawnEditor
          path: artifact/PawnEditor/
